name: Cypress E2E Test Run

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      target_env:
        description: 'Select environment to test'
        required: true
        default: 'DEV'
        type: choice
        options:
          - DEV
          - TEST

permissions:
  contents: read
  actions: read

jobs:
  test:
    runs-on: uhg-runner

    strategy:
      matrix:
        ENV_NAME: ${{ fromJson(format('["{0}"]', github.event.inputs.target_env || 'TEST')) }}

    steps:
      - name: Skip non-selected environment (manual trigger only)
        if: github.event_name == 'workflow_dispatch' && matrix.ENV_NAME != github.event.inputs.target_env
        run: echo "Skipping environment ${{ matrix.ENV_NAME }} because target_env is ${{ github.event.inputs.target_env }}."
        shell: bash

      - name: Cleanup
        run: sudo chown -R $USER:$USER $GITHUB_WORKSPACE

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Installing Cypress Dependencies and xvfb
        if: runner.os == 'Linux'
        run: |
          wget https://repo1.uhc.com/artifactory/security-ubuntu-cache/ubuntu/pool/main/x/xorg-server/xserver-common_21.1.4-2ubuntu1.7~22.04.9_all.deb -O /tmp/xserver-common.deb
          wget https://repo1.uhc.com/artifactory/security-ubuntu-cache/ubuntu/pool/universe/x/xorg-server/xvfb_21.1.3-2ubuntu2.9_amd64.deb -O /tmp/xvfb.deb
          sudo apt-get update
          sudo apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libasound2t64 libxtst6 xauth /tmp/xserver-common.deb /tmp/xvfb.deb
          rm /tmp/xserver-common.deb /tmp/xvfb.deb

      - name: npm Install
        run: |
          npm config set registry https://repo1.uhc.com/artifactory/api/npm/npm-virtual/
          npm install

      - name: Create Cypress Reports Directory (Admin)
        run: |
          export REPORT_PATH="cypress/reports/test/admin/$(date +'%Y-%m-%d_%H-%M-%S')"
          mkdir -p "$REPORT_PATH"
          echo "ADMIN_REPORT_PATH=$REPORT_PATH" >> $GITHUB_ENV

      - name: Run Admin Tests (TEST)
        run: |
          echo "BASE_URL=${{ secrets.TEST_BASE_URL }}" >> $GITHUB_ENV
          echo "USERNAME=${{ secrets.TEST_ADMIN_USERNAME }}" >> $GITHUB_ENV
          echo "PASSWORD=${{ secrets.TEST_ADMIN_PASSWORD }}" >> $GITHUB_ENV

          echo "Running ADMIN tests on TEST"
          npx cypress run --spec "cypress/e2e/admin/features/**/*.feature" --env BASE_URL=$BASE_URL,USERNAME=$USERNAME,PASSWORD=$PASSWORD,REPORT_PATH=$ADMIN_REPORT_PATH
        env:
          BASE_URL: ${{ secrets.TEST_BASE_URL }}
          USERNAME: ${{ secrets.TEST_ADMIN_USERNAME }}
          PASSWORD: ${{ secrets.TEST_ADMIN_PASSWORD }}

      - name: Upload Admin Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-report-test-admin
          path: |
            ${{ env.ADMIN_REPORT_PATH }}
            cypress/screenshots
            cypress/videos

      - name: Create Cypress Reports Directory (Analyst)
        run: |
          export REPORT_PATH="cypress/reports/test/analyst/$(date +'%Y-%m-%d_%H-%M-%S')"
          mkdir -p "$REPORT_PATH"
          echo "ANALYST_REPORT_PATH=$REPORT_PATH" >> $GITHUB_ENV

      - name: Run Analyst Tests (TEST)
        run: |
          echo "BASE_URL=${{ secrets.TEST_BASE_URL }}" >> $GITHUB_ENV
          echo "USERNAME=${{ secrets.TEST_ANALYST_USERNAME }}" >> $GITHUB_ENV
          echo "PASSWORD=${{ secrets.TEST_ANALYST_PASSWORD }}" >> $GITHUB_ENV

          echo "Running ANALYST tests on TEST"
          npx cypress run --spec "cypress/e2e/analyst/features/**/*.feature" --env BASE_URL=$BASE_URL,USERNAME=$USERNAME,PASSWORD=$PASSWORD,REPORT_PATH=$ANALYST_REPORT_PATH
        env:
          BASE_URL: ${{ secrets.TEST_BASE_URL }}
          USERNAME: ${{ secrets.TEST_ANALYST_USERNAME }}
          PASSWORD: ${{ secrets.TEST_ANALYST_PASSWORD }}

      - name: Upload Analyst Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-report-test-analyst
          path: |
            ${{ env.ANALYST_REPORT_PATH }}
            cypress/screenshots
            cypress/videos
